import { ColorPalette } from '../types';

export const PALETTES: Record<string, ColorPalette> = {
  neon: {
    id: 'neon',
    name: 'Cyber Neon',
    primary: '#00f0ff',
    secondary: '#ff007f',
    background: '#07080d',
    glow: '#00f0ff',
    accent: '#00ff88',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Night City',
    primary: '#fcee0a',
    secondary: '#ff0055',
    background: '#05040a',
    glow: '#ff0055',
    accent: '#00e5ff',
  },
  synthwave: {
    id: 'synthwave',
    name: 'Outrun Synthwave',
    primary: '#ff71ce',
    secondary: '#01cdfe',
    background: '#0b001a',
    glow: '#ff71ce',
    accent: '#05ffa1',
  },
  fire: {
    id: 'fire',
    name: 'Solar Flare',
    primary: '#ff3b00',
    secondary: '#ffaa00',
    background: '#0d0401',
    glow: '#ff5500',
    accent: '#fff275',
  },
  ice: {
    id: 'ice',
    name: 'Glacial Aurora',
    primary: '#a6e3e9',
    secondary: '#71c9ce',
    background: '#03080e',
    glow: '#3a98b9',
    accent: '#e3fdfd',
  },
  aurora: {
    id: 'aurora',
    name: 'Northern Lights',
    primary: '#00ffb2',
    secondary: '#9d4edd',
    background: '#020b08',
    glow: '#00ffb2',
    accent: '#5a189a',
  },
  acid: {
    id: 'acid',
    name: 'Acid Matrix',
    primary: '#39ff14',
    secondary: '#ccff00',
    background: '#030a03',
    glow: '#39ff14',
    accent: '#76ff03',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Studio Minimalist',
    primary: '#ffffff',
    secondary: '#888899',
    background: '#090a0f',
    glow: '#ffffff',
    accent: '#bbbbcc',
  },
  sunset: {
    id: 'sunset',
    name: 'Miami Dusk',
    primary: '#ff5e7e',
    secondary: '#ff9966',
    background: '#0e0612',
    glow: '#ff5e7e',
    accent: '#ffd166',
  },
  electric: {
    id: 'electric',
    name: 'Electric Arc',
    primary: '#00a8ff',
    secondary: '#9c88ff',
    background: '#040714',
    glow: '#00a8ff',
    accent: '#fbc531',
  }
};
