import { XYOscilloscopeConfig, VisualPreset } from '../types';
import { PALETTES } from './palettes';

export interface XYPresetDefinition {
  id: string;
  name: string;
  description: string;
  config: Partial<XYOscilloscopeConfig>;
  paletteId: string;
  glow: number;
  trail: number;
}

export const XY_FLAGSHIP_PRESETS: XYPresetDefinition[] = [
  {
    id: 'xy-classic-lissajous',
    name: '1. Classic Lissajous',
    description: 'Analog cathode-ray tube precision XY figure-eight with continuous harmonic morphing',
    paletteId: 'electric',
    glow: 0.9,
    trail: 0.8,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'neon',
      freqRatioX: 1,
      freqRatioY: 2,
      ratioPreset: '1:2',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.6,
      reactivePhase: true,
      ampX: 1.0,
      ampY: 1.0,
      overallScale: 1.0,
      thickness: 3.5,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      distortionAmount: 0.1,
      symmetry: 1,
      kaleidoscope: false,
      glowIntensity: 1.2,
      glowRadius: 28,
      gradientAlongCurve: true,
      gradientStartColor: '#00f0ff',
      gradientMidColor: '#00a8ff',
      gradientEndColor: '#9c88ff',
      particleEmission: false,
      rotationSpeed: 0.05
    }
  },
  {
    id: 'xy-neon-heart',
    name: '2. Neon Heart',
    description: 'Pulsing cardioid parametric geometry vibrating to kick transients and sub-bass',
    paletteId: 'neon',
    glow: 1.1,
    trail: 0.7,
    config: {
      sourceMode: 'bass-treble',
      beamStyle: 'neon',
      freqRatioX: 1,
      freqRatioY: 1,
      ratioPreset: '1:1',
      reactiveFrequencyRatio: false,
      phaseSpeed: 0.3,
      reactivePhase: true,
      ampX: 1.1,
      ampY: 1.2,
      overallScale: 1.1,
      thickness: 4.0,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'wave',
      distortionAmount: 0.15,
      symmetry: 2,
      kaleidoscope: false,
      glowIntensity: 1.4,
      glowRadius: 32,
      gradientAlongCurve: true,
      gradientStartColor: '#ff007f',
      gradientMidColor: '#ff0055',
      gradientEndColor: '#00f0ff',
      particleEmission: true,
      rotationSpeed: 0.0
    }
  },
  {
    id: 'xy-infinite-loop',
    name: '3. Infinite Loop',
    description: 'Hypnotic lemniscate infinity ribbon twisting through multi-dimensional phase space',
    paletteId: 'synthwave',
    glow: 1.0,
    trail: 0.85,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'gradient',
      freqRatioX: 2,
      freqRatioY: 3,
      ratioPreset: '2:3',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.8,
      reactivePhase: true,
      ampX: 1.2,
      ampY: 0.9,
      overallScale: 1.05,
      thickness: 3.5,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      symmetry: 1,
      kaleidoscope: false,
      glowIntensity: 1.1,
      glowRadius: 26,
      gradientAlongCurve: true,
      gradientStartColor: '#ff71ce',
      gradientMidColor: '#01cdfe',
      gradientEndColor: '#05ffa1',
      particleEmission: true,
      rotationSpeed: 0.15
    }
  },
  {
    id: 'xy-crystal',
    name: '4. Crystal',
    description: 'Sharp faceted mineral lattice with 6-fold radial symmetry and harmonic spikes',
    paletteId: 'ice',
    glow: 0.9,
    trail: 0.65,
    config: {
      sourceMode: 'mid-high',
      beamStyle: 'solid',
      freqRatioX: 3,
      freqRatioY: 4,
      ratioPreset: '3:4',
      reactiveFrequencyRatio: false,
      phaseSpeed: 0.4,
      reactivePhase: false,
      ampX: 1.0,
      ampY: 1.0,
      overallScale: 1.0,
      thickness: 2.5,
      reactiveLineWidth: false,
      velocityModulation: true,
      distortionType: 'frequency',
      distortionAmount: 0.25,
      symmetry: 6,
      kaleidoscope: true,
      glowIntensity: 1.0,
      glowRadius: 22,
      gradientAlongCurve: false,
      particleEmission: false,
      rotationSpeed: 0.2
    }
  },
  {
    id: 'xy-aurora',
    name: '5. Aurora',
    description: 'Silky polar ribbons drifting with Northern Lights emerald and violet luminescence',
    paletteId: 'aurora',
    glow: 1.2,
    trail: 0.85,
    config: {
      sourceMode: 'bass-mid',
      beamStyle: 'neon',
      freqRatioX: 1,
      freqRatioY: 2,
      ratioPreset: '1:2',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.5,
      reactivePhase: true,
      ampX: 1.1,
      ampY: 1.1,
      overallScale: 1.0,
      thickness: 3.8,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'radial',
      distortionAmount: 0.2,
      symmetry: 2,
      kaleidoscope: false,
      glowIntensity: 1.3,
      glowRadius: 35,
      gradientAlongCurve: true,
      gradientStartColor: '#00ffb2',
      gradientMidColor: '#5a189a',
      gradientEndColor: '#9d4edd',
      particleEmission: true,
      rotationSpeed: -0.1
    }
  },
  {
    id: 'xy-cyber-tunnel',
    name: '6. Cyber Tunnel',
    description: 'High-speed parametric wormhole projecting nested trajectories into infinite depth',
    paletteId: 'cyberpunk',
    glow: 1.0,
    trail: 0.8,
    config: {
      sourceMode: 'stereo',
      beamStyle: 'multiline',
      freqRatioX: 2,
      freqRatioY: 5,
      ratioPreset: 'custom',
      reactiveFrequencyRatio: true,
      phaseSpeed: 1.0,
      reactivePhase: true,
      ampX: 1.2,
      ampY: 1.2,
      overallScale: 1.15,
      thickness: 3.0,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      symmetry: 4,
      kaleidoscope: false,
      glowIntensity: 1.2,
      glowRadius: 30,
      gradientAlongCurve: true,
      gradientStartColor: '#fcee0a',
      gradientMidColor: '#ff0055',
      gradientEndColor: '#00e5ff',
      particleEmission: true,
      rotationSpeed: 0.35,
      beatRotationImpulse: true
    }
  },
  {
    id: 'xy-kaleidoscope',
    name: '7. Kaleidoscope',
    description: 'Hypnotic 12-way mirrored mandala unfolding with sacred geometry',
    paletteId: 'fire',
    glow: 1.1,
    trail: 0.7,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'neon',
      freqRatioX: 3,
      freqRatioY: 5,
      ratioPreset: '3:5',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.6,
      reactivePhase: true,
      ampX: 0.9,
      ampY: 0.9,
      overallScale: 0.95,
      thickness: 3.0,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      symmetry: 12,
      kaleidoscope: true,
      glowIntensity: 1.2,
      glowRadius: 28,
      gradientAlongCurve: true,
      gradientStartColor: '#ff3b00',
      gradientMidColor: '#ffaa00',
      gradientEndColor: '#fff275',
      particleEmission: false,
      rotationSpeed: 0.15
    }
  },
  {
    id: 'xy-electric-flower',
    name: '8. Electric Flower',
    description: 'Blooming 8-petal neon lotus pulsing to snare snaps and vocal frequencies',
    paletteId: 'neon',
    glow: 1.2,
    trail: 0.75,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'neon',
      freqRatioX: 3,
      freqRatioY: 4,
      ratioPreset: '3:4',
      reactiveFrequencyRatio: false,
      phaseSpeed: 0.45,
      reactivePhase: true,
      ampX: 1.0,
      ampY: 1.0,
      overallScale: 1.05,
      thickness: 3.5,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'radial',
      distortionAmount: 0.25,
      symmetry: 8,
      kaleidoscope: true,
      glowIntensity: 1.3,
      glowRadius: 30,
      gradientAlongCurve: true,
      gradientStartColor: '#00f0ff',
      gradientMidColor: '#ff007f',
      gradientEndColor: '#00ff88',
      particleEmission: true,
      rotationSpeed: 0.1
    }
  },
  {
    id: 'xy-plasma-orbit',
    name: '9. Plasma Orbit',
    description: 'Quantum gravitational trajectory with trailing energetic plasma nodes',
    paletteId: 'acid',
    glow: 1.15,
    trail: 0.85,
    config: {
      sourceMode: 'stereo',
      beamStyle: 'neon',
      freqRatioX: 4,
      freqRatioY: 5,
      ratioPreset: '4:5',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.7,
      reactivePhase: true,
      ampX: 1.1,
      ampY: 1.1,
      overallScale: 1.0,
      thickness: 3.5,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'wave',
      distortionAmount: 0.2,
      symmetry: 1,
      kaleidoscope: false,
      glowIntensity: 1.25,
      glowRadius: 32,
      gradientAlongCurve: true,
      gradientStartColor: '#39ff14',
      gradientMidColor: '#ccff00',
      gradientEndColor: '#76ff03',
      particleEmission: true,
      rotationSpeed: 0.25
    }
  },
  {
    id: 'xy-quantum-wave',
    name: '10. Quantum Wave',
    description: 'Multi-layer interference pattern modeling electron orbital wavefunctions',
    paletteId: 'electric',
    glow: 1.0,
    trail: 0.8,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'multiline',
      freqRatioX: 5,
      freqRatioY: 6,
      ratioPreset: '5:6',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.55,
      reactivePhase: true,
      ampX: 1.0,
      ampY: 1.0,
      overallScale: 1.0,
      thickness: 2.8,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      symmetry: 2,
      kaleidoscope: false,
      glowIntensity: 1.1,
      glowRadius: 25,
      gradientAlongCurve: true,
      gradientStartColor: '#00a8ff',
      gradientMidColor: '#9c88ff',
      gradientEndColor: '#fbc531',
      particleEmission: false,
      rotationSpeed: -0.1
    }
  },
  {
    id: 'xy-bass-reactor',
    name: '11. Bass Reactor',
    description: 'Explosive sub-bass displacement engine expanding into 4-quadrant shockwaves',
    paletteId: 'fire',
    glow: 1.3,
    trail: 0.7,
    config: {
      sourceMode: 'bass-mid',
      beamStyle: 'neon',
      freqRatioX: 1,
      freqRatioY: 2,
      ratioPreset: '1:2',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.4,
      reactivePhase: true,
      ampX: 1.3,
      ampY: 1.3,
      overallScale: 1.15,
      thickness: 5.0,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'radial',
      distortionAmount: 0.35,
      symmetry: 4,
      kaleidoscope: true,
      glowIntensity: 1.5,
      glowRadius: 40,
      gradientAlongCurve: true,
      gradientStartColor: '#ff3b00',
      gradientMidColor: '#ff0055',
      gradientEndColor: '#ffaa00',
      particleEmission: true,
      rotationSpeed: 0.05,
      beatRotationImpulse: true
    }
  },
  {
    id: 'xy-stereo-pulse',
    name: '12. Stereo Pulse',
    description: 'Direct Left vs Right channel phase correlation oscilloscope with authentic stereo imaging',
    paletteId: 'neon',
    glow: 1.0,
    trail: 0.8,
    config: {
      sourceMode: 'stereo',
      beamStyle: 'neon',
      freqRatioX: 1,
      freqRatioY: 1,
      ratioPreset: '1:1',
      reactiveFrequencyRatio: false,
      phaseSpeed: 0.0,
      reactivePhase: false,
      ampX: 1.3,
      ampY: 1.3,
      overallScale: 1.1,
      thickness: 3.5,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      symmetry: 1,
      kaleidoscope: false,
      glowIntensity: 1.2,
      glowRadius: 28,
      gradientAlongCurve: true,
      gradientStartColor: '#00f0ff',
      gradientMidColor: '#a855f7',
      gradientEndColor: '#ff007f',
      particleEmission: true,
      rotationSpeed: 0.0
    }
  },
  {
    id: 'xy-dream-spiral',
    name: '13. Dream Spiral',
    description: 'Logarithmic golden-ratio spiral rotating into deep luminous cyan dreamscapes',
    paletteId: 'synthwave',
    glow: 1.1,
    trail: 0.88,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'gradient',
      freqRatioX: 5,
      freqRatioY: 7,
      ratioPreset: '5:7',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.75,
      reactivePhase: true,
      ampX: 1.1,
      ampY: 1.1,
      overallScale: 1.0,
      thickness: 3.2,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'none',
      polarMode: true,
      polarRings: 2,
      symmetry: 1,
      kaleidoscope: false,
      glowIntensity: 1.2,
      glowRadius: 30,
      gradientAlongCurve: true,
      gradientStartColor: '#ff71ce',
      gradientMidColor: '#01cdfe',
      gradientEndColor: '#05ffa1',
      particleEmission: true,
      rotationSpeed: 0.2
    }
  },
  {
    id: 'xy-digital-dna',
    name: '14. Digital DNA',
    description: 'Double helical rotating trajectory simulating genetic molecular vibrations',
    paletteId: 'aurora',
    glow: 1.0,
    trail: 0.8,
    config: {
      sourceMode: 'mid-high',
      beamStyle: 'neon',
      freqRatioX: 2,
      freqRatioY: 7,
      ratioPreset: 'custom',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.9,
      reactivePhase: true,
      ampX: 0.8,
      ampY: 1.3,
      overallScale: 1.05,
      thickness: 3.5,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'wave',
      distortionAmount: 0.15,
      symmetry: 2,
      kaleidoscope: false,
      glowIntensity: 1.15,
      glowRadius: 26,
      gradientAlongCurve: true,
      gradientStartColor: '#00ffb2',
      gradientMidColor: '#9d4edd',
      gradientEndColor: '#00e5ff',
      particleEmission: false,
      rotationSpeed: 0.15
    }
  },
  {
    id: 'xy-hyper-geometry',
    name: '15. Hyper Geometry',
    description: '4-dimensional hypercube tesseract projection folding through 16-way radial kaleidoscope space',
    paletteId: 'cyberpunk',
    glow: 1.2,
    trail: 0.75,
    config: {
      sourceMode: 'synthesized',
      beamStyle: 'neon',
      freqRatioX: 7,
      freqRatioY: 8,
      ratioPreset: '7:8',
      reactiveFrequencyRatio: true,
      phaseSpeed: 0.85,
      reactivePhase: true,
      ampX: 1.0,
      ampY: 1.0,
      overallScale: 0.95,
      thickness: 3.0,
      reactiveLineWidth: true,
      velocityModulation: true,
      distortionType: 'frequency',
      distortionAmount: 0.3,
      symmetry: 16,
      kaleidoscope: true,
      glowIntensity: 1.3,
      glowRadius: 30,
      gradientAlongCurve: true,
      gradientStartColor: '#fcee0a',
      gradientMidColor: '#ff0055',
      gradientEndColor: '#00e5ff',
      particleEmission: true,
      rotationSpeed: 0.2,
      beatRotationImpulse: true
    }
  }
];
